<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2021-05-09T23:58:05 BRT" name="Default suite" finished-at="2021-05-09T23:58:07 BRT" duration-ms="2656">
    <groups>
    </groups>
    <test started-at="2021-05-09T23:58:05 BRT" name="Default test" finished-at="2021-05-09T23:58:07 BRT" duration-ms="2656">
      <class name="br.com.rafaelferreira.rest.test.SimulacaoCreditoTest">
        <test-method is-config="true" signature="setup()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:05 BRT" name="setup" finished-at="2021-05-09T23:58:05 BRT" duration-ms="620" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:05 BRT" name="beforeMethod" finished-at="2021-05-09T23:58:05 BRT" duration-ms="31" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="CT_01_getCPFComRestricao()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:05 BRT" name="CT_01_getCPFComRestricao" finished-at="2021-05-09T23:58:07 BRT" duration-ms="1109" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at br.com.rafaelferreira.validate.Acceptance.validaBodyAlert(Acceptance.java:28)
at br.com.rafaelferreira.rest.test.SimulacaoCreditoTest.CT_01_getCPFComRestricao(SimulacaoCreditoTest.java:50)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CT_01_getCPFComRestricao -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:07 BRT" name="beforeMethod" finished-at="2021-05-09T23:58:07 BRT" duration-ms="7" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="CT_02_getCPFSemRestricao()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:07 BRT" name="CT_02_getCPFSemRestricao" finished-at="2021-05-09T23:58:07 BRT" duration-ms="150" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CT_02_getCPFSemRestricao -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:07 BRT" name="beforeMethod" finished-at="2021-05-09T23:58:07 BRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="CT_03_postSimulacao()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:07 BRT" name="CT_03_postSimulacao" finished-at="2021-05-09T23:58:07 BRT" duration-ms="402" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CT_03_postSimulacao -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:07 BRT" name="beforeMethod" finished-at="2021-05-09T23:58:07 BRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="CT_04_putSimulacao()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:07 BRT" name="CT_04_putSimulacao" finished-at="2021-05-09T23:58:07 BRT" duration-ms="68" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at br.com.rafaelferreira.validate.Acceptance.validaBody(Acceptance.java:41)
at br.com.rafaelferreira.rest.test.SimulacaoCreditoTest.CT_04_putSimulacao(SimulacaoCreditoTest.java:79)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CT_04_putSimulacao -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:07 BRT" name="beforeMethod" finished-at="2021-05-09T23:58:07 BRT" duration-ms="2" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="CT_05_getSimulacao()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:07 BRT" name="CT_05_getSimulacao" finished-at="2021-05-09T23:58:07 BRT" duration-ms="188" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CT_05_getSimulacao -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:07 BRT" name="beforeMethod" finished-at="2021-05-09T23:58:07 BRT" duration-ms="1" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="CT_06_deleteSimulacao()[pri:0, instance:br.com.rafaelferreira.rest.test.SimulacaoCreditoTest@515aebb0]" started-at="2021-05-09T23:58:07 BRT" name="CT_06_deleteSimulacao" finished-at="2021-05-09T23:58:07 BRT" duration-ms="32" status="FAIL">
          <exception class="java.lang.RuntimeException">
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException
at br.com.rafaelferreira.validate.Acceptance.validaStatusCode(Acceptance.java:54)
at br.com.rafaelferreira.rest.test.SimulacaoCreditoTest.CT_06_deleteSimulacao(SimulacaoCreditoTest.java:102)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:599)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:822)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1510)
at org.testng.TestRunner.privateRun(TestRunner.java:764)
at org.testng.TestRunner.run(TestRunner.java:585)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CT_06_deleteSimulacao -->
      </class> <!-- br.com.rafaelferreira.rest.test.SimulacaoCreditoTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
